services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev-charger-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ev_charger_system?schema=public
      - DEBUG=prisma:*,express:*
      - LOG_LEVEL=debug
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ev-charger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:17
    container_name: ev-charger-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ev_charger_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ev-charger-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  ev-charger-network:
    driver: bridge

volumes:
  postgres_data: 